# Generated by Django 4.0.1 on 2022-01-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='token',
            new_name='password',
        ),
    ]
