# Generated by Django 4.0.1 on 2022-01-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(max_length=200, upload_to='avatar/%Y/%m'),
        ),
    ]
