# Generated by Django 4.0.1 on 2022-01-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', max_length=200, upload_to='avatar/%Y'),
        ),
    ]
