# Generated by Django 4.0.1 on 2022-01-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
